# Generated by Django 3.0.7 on 2022-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
