# Generated by Django 3.0.7 on 2022-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220223_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
