# Generated by Django 3.0.7 on 2022-02-24 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220224_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
