# Generated by Django 3.0.7 on 2022-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timelog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
