# Generated by Django 3.0.7 on 2022-02-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220224_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
