# Generated by Django 4.0.2 on 2022-02-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
