# Generated by Django 3.0.7 on 2022-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220223_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='is_started',
            new_name='is_running',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='is_stoped',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
