# Generated by Django 3.0.7 on 2022-02-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220224_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='start',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='stop',
            new_name='stopped_at',
        ),
    ]
