# Generated by Django 3.0.7 on 2022-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220223_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
