# Generated by Django 3.0.7 on 2022-02-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20220223_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
