# Generated by Django 3.0.7 on 2022-02-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20220223_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
